# Generated by Django 4.2 on 2025-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_fitapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.IntegerField(default=0),
        ),
    ]
