# Generated by Django 4.2 on 2025-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_fitapp", "0002_booking_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_phone",
            field=models.CharField(default="", max_length=100),
        ),
    ]
