# Generated by Django 4.2 on 2025-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_fitapp", "0003_booking_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessclass",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
